version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    volumes:
      - ./images:/usr/share/nginx/html/images:ro # 이미지 파일을 읽기 전용으로 마운트
    depends_on:
      - backend
    networks:
      - vote-app-network

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      REDIS_HOST: redis # Redis 서비스 이름
      REDIS_PORT: 6379 # Redis 기본 포트
    depends_on:
      - redis # Redis 서비스가 먼저 시작되어야 함
    networks:
      - vote-app-network

  redis:
    image: "redis:latest"
    volumes:
      - redis_data:/data # Redis 데이터 영속성 유지
    networks:
      - vote-app-network

volumes:
  redis_data:
networks: # bridge network 자동 생성 (vote-app-network)
  vote-app-network:
    driver: bridge